import React, { Suspense, useRef } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import { ContactShadows, useGLTF, OrbitControls } from '@react-three/drei'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

useGLTF.preload('/OutsideTheBox.glb')
function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/OutsideTheBox.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[0.04, 0, 0.95]} rotation={[0, 0.03, 0]} scale={[0.55, 0.45, 0.47]}>
        <mesh geometry={nodes.Vert.geometry} material={nodes.Vert.material} position={[0.17, 0, -1.55]} rotation={[0, -0.03, 0]} scale={[2.04, 1.99, 2.01]}>
          <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-1.33, 0, -1.41]} scale={[0.43, 0.6, 0.75]} />
          <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-0.66, 0, -1.44]} scale={[0.34, 0.57, 0.68]} />
          <mesh geometry={nodes.Vert001_1.geometry} material={nodes.Vert001_1.material} position={[-0.65, -0.03, 0.07]} scale={[0.85, 1, 0.95]} />
          <mesh geometry={nodes.Vert003.geometry} material={nodes.Vert003.material} position={[-0.31, 0, -0.98]} scale={[0.71, 1.11, 1.23]} />
          <mesh geometry={nodes.Vert005.geometry} material={nodes.Vert005.material} position={[-0.05, 0, -0.08]} scale={[0.95, 1.11, 1.23]} />
          <mesh geometry={nodes.Vert006.geometry} material={nodes.Vert006.material} position={[-0.01, 0, -0.1]} scale={[0.95, 1.78, 1.23]} />
        </mesh>
        <mesh geometry={nodes.Vert002.geometry} material={nodes.Vert002.material} position={[1.39, 0.01, -1.99]} rotation={[0, 0.16, 0]} scale={[1.91, 1.44, 1.28]} />
        <mesh geometry={nodes.Vert004.geometry} material={nodes.Vert004.material} position={[0.31, 0, -1.77]} rotation={[0, -0.05, 0]} scale={[1.96, 1.08, 1.77]} />
        <mesh geometry={nodes.Vert008.geometry} material={nodes.Vert008.material} position={[1.97, 0, -3.44]} rotation={[0, -0.03, 0]} scale={[1.07, 1.46, 1.64]} />
        <mesh geometry={nodes.Vert009.geometry} material={nodes.Vert009.material} position={[3.02, 0.01, -4.24]} rotation={[0, -0.03, 0]} scale={[1.63, 1.51, 2.48]} />
        <mesh geometry={nodes.Vert012.geometry} material={nodes.Vert012.material} position={[0.25, 0, -1.75]} scale={[1.96, 1.3, 1.77]} />
      </mesh>
    </group>
  )
}

export default function App() {
  return (
    <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 0, 7.9], fov: 50 }}>
      <directionalLight position={[30, -10, 12.5]} intensity={1} color={'#2299ff'} />
      <directionalLight position={[-10, 10, 12.5]} intensity={1} color={'#ffffff'} />
      <Suspense fallback={null}>
        <OrbitControls />
        <Suspense fallback={null}>
          <Model rotation={[90, 0, 0]} position={[0, 0, 0]} />
        </Suspense>
        <ContactShadows frames={1} rotation-x={[Math.PI / 2]} position={[0, -0.33, 0]} far={0.4} width={2} height={2} blur={4} />
      </Suspense>
    </Canvas>
  )
}
