/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Circle002.geometry} material={nodes.Circle002.material} position={[0.04, 0, 0.95]} rotation={[0, 0.03, 0]} scale={[0.55, 0.45, 0.47]}>
          <mesh geometry={nodes.Vert004.geometry} material={nodes.Vert004.material} position={[0.31, 0, -1.77]} rotation={[0, -0.05, 0]} scale={[1.96, 1.08, 1.77]} />
          <mesh geometry={nodes.Vert.geometry} material={nodes.Vert.material} position={[0.17, 0, -1.55]} rotation={[0, -0.03, 0]} scale={[2.04, 1.99, 2.01]}>
            <mesh geometry={nodes.Circle.geometry} material={nodes.Circle.material} position={[-1.33, 0, -1.41]} scale={[0.43, 0.6, 0.75]} />
            <mesh geometry={nodes.Circle001.geometry} material={nodes.Circle001.material} position={[-0.66, 0, -1.44]} scale={[0.34, 0.57, 0.68]} />
            <mesh geometry={nodes.Vert003.geometry} material={nodes.Vert003.material} position={[-0.31, 0, -0.98]} scale={[0.71, 1.11, 1.23]} />
            <mesh geometry={nodes.Vert001_1.geometry} material={nodes.Vert001_1.material} position={[-0.65, -0.03, 0.07]} scale={[0.85, 1, 0.95]} />
            <mesh geometry={nodes.Vert005.geometry} material={nodes.Vert005.material} position={[-0.05, 0, -0.08]} scale={[0.95, 1.11, 1.23]} />
            <mesh geometry={nodes.Vert006.geometry} material={nodes.Vert006.material} position={[-0.01, 0, -0.1]} scale={[0.95, 1.78, 1.23]} />
          </mesh>
          <mesh geometry={nodes.Vert002.geometry} material={nodes.Vert002.material} position={[1.39, 0.01, -1.99]} rotation={[0, 0.16, 0]} scale={[1.91, 1.44, 1.28]} />
          <mesh geometry={nodes.Vert008.geometry} material={nodes.Vert008.material} position={[1.97, 0, -3.44]} rotation={[0, -0.03, 0]} scale={[1.07, 1.46, 1.64]} />
          <mesh geometry={nodes.Vert009.geometry} material={nodes.Vert009.material} position={[3.02, 0.01, -4.24]} rotation={[0, -0.03, 0]} scale={[1.63, 1.51, 2.48]} />
          <mesh geometry={nodes.Vert012.geometry} material={nodes.Vert012.material} position={[0.25, 0, -1.75]} scale={[1.96, 1.3, 1.77]} />
        </mesh>
      </group>
      <PerspectiveCamera makeDefault={false} position={[0, 0, 7.99]} />
      <directionalLight intensity={1} decay={2} color="#ff571f" position={[-0.61, 9.5, 12.96]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
